-- Configs.luau
-- /ReplicatedStorage/Modules/Configs.luau

local Configs = {
    ['BronzeAxe'] = {
        Name = 'Bronze Axe',
        Description = 'Bronze',
        Model = 'BronzeAxe',
        Icon = 'rbxassetid://138890925012163',
    },
    ['IronAxe'] = {
        Name = 'Iron Axe',
        Description = 'Ferro',
        Model = 'IronAxe',
        Icon = 'rbxassetid://87960543898534',
    },
    ['GoldenAxe'] = {
        Name = 'Golden Axe',
        Description = 'Ouro',
        Model = 'GoldenAxe',
        Icon = 'rbxassetid://100646766211037',
    },
}

return Configs