-- Configs.luau
-- /ReplicatedStorage/Modules/Configs.luau

local Configs = {
    ['1'] = {
        Name = 'Bronze Axe',
        Description = 'Bronze',
        Model = 'BronzeAxe',
        Icon = ''
    },
    ['2'] = {
        Name = 'Iron Axe',
        Description = 'Ferro',
        Model = 'IronAxe',
        Icon = ''
    },
    ['3'] = {
        Name = 'Golden Axe',
        Description = 'Ouro',
        Model = 'GoldenAxe',
    },
}

return Configs